### ISSUE TITLE
🐛 Bug: yarn zip fails after cloning the repo

### ISSUE THREAD

**Issue by ad0ran** [JoshuaKGoldberg/refined-saved-replies#38]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/refined-saved-replies/issues?q=is%3Aissue+label%3A%22type%3A+bug%22) and found none that matched my issue.

### Expected

running `yarn zip` should zip the build files correctly

### Actual

node fails to find the files the manifest.json file is referring to

### Additional Info

There's problem when trying to run the `yarn zip` command for the project.
The manifest.json file refers to a bunch of icon's that don't seem to exist.

```
"icons": {
  "16": "assets/icon16.png",
  "32": "assets/icon32.png",
  "48": "assets/icon48.png",
  "64": "assets/icon64.png",
  "128": "assets/icon128.png"
},
```

![image](https://user-images.githubusercontent.com/1423613/197030449-05618cd7-b975-4792-8f58-da2cd01db708.png)

**Comment by JoshuaKGoldberg** [comment]
Looks like I never checked in the icons. Weird. Thanks for posting @ad0ran - I'll have this fixed in a minute!

**Comment by JoshuaKGoldberg** [comment]
Ok @ad0ran this should be fixed now! If you pull in the latest changes from the `main` branch, the icons should exist locally. Let me know if anything else is broken or you'd like help with that! 🙂
