### ISSUE TITLE
🚀 Feature: Also support pull requests

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/refined-saved-replies#42]
### Feature Request Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/refined-saved-replies/issues?q=is%3Aissue+label%3A%22type%3A+feature%22) and found none that matched my issue.

### Overview

PRs also have a reply field that's compatible with saved replies. This extension should support URLs like `https://github.com/*/*/pull/*` too!

**Comment by Jolg42** [comment]
I created a PR ✨ 
https://github.com/JoshuaKGoldberg/refined-saved-replies/pull/147
