### ISSUE TITLE
🚀 Feature: Add handlebars/mustache templating based on the original issue/PR

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/refined-saved-replies#45]
### Feature Request Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/refined-saved-replies/issues?q=is%3Aissue+label%3A%22type%3A+feature%22) and found none that matched my issue.

### Overview

I'd like to be able to set up a template that includes lines like `Thanks for reporting, {{ reporter }}!` -- where the `{{ reporter }}` is the name of the person who filed the issue. https://www.npmjs.com/package/mustache is a very good templating engine we could use to power this.

**Comment by Pinjasaur** [comment]
I was thinking of this exact feature. I wasn't sure if Saved Replies had basic templating support natively or not, but it doesn't really matter since it can be solved "JIT" style e.g. at runtime with the extension. Any other templating `{{ key }}`s that would be worth supporting too?

**Comment by JoshuaKGoldberg** [comment]
Great question 😄. Putting a little more thought into it, maybe a starting set like...
* `author`: probably a better name than `reporter`, so it'd be the same for PRs?
* `branch` (PR only)
* `commits` (PR only)
* `issue` (for PRs, including linked issue - if it exists)
* `pr` (PR only)
* `organization`
* `repository`

If we were working for GitHub & making this a "real" figure I'd want to put much more thought into this, and consider having nested objects like `repository.full_url`. But for the sake of simplicity & trying things out I think it'd be good to get just a limited set of things. If you want to just put the easiest from that list, and leave the remaining ones as `good first issue`s.

**Comment by JoshuaKGoldberg** [comment]
We're chatting on a 1:1 and talking about how the GitHub REST API has basically all this info!

* Issue: https://api.github.com/repos/JoshuaKGoldberg/refined-saved-replies/issues/45
* PR: https://api.github.com/repos/JoshuaKGoldberg/refined-saved-replies/pulls/67
