### ISSUE TITLE
🛠 Tooling: add an `.editorconfig` file

### ISSUE THREAD

**Issue by Pinjasaur** [JoshuaKGoldberg/refined-saved-replies#51]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/refined-saved-replies/issues?q=is%3Aissue+label%3A%22area%3A+tooling%22) and found none that matched my issue.

### Overview

https://editorconfig.org/

Provides a way to maintain consistent styling across editors.

An example one, from one of my personal projects: https://github.com/Pinjasaur/bic/blob/master/.editorconfig

### Additional Info

The only downside is upon creating the file it'll need to be _applied_ to existing files. Sort of like `.gitignore-`ing a file _after_ it's already been tracked: some manual intervention needs to happen.

**Comment by JoshuaKGoldberg** [comment]
Ah thanks for filing this - once in a while I see one and haven't looked into them yet!

My only concern would be that we don't want to intersect with Prettier settings. But, it looks like [Prettier already recognizes `.editorconfig`](https://prettier.io/docs/en/options.html#tabs) - so great! We can switch from `.prettierrc*` to `.editorconfig`.
