### ISSUE TITLE
🧹 Cleanup: Use an observer on saved replies button click, not a quick setTimeout loop

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/refined-saved-replies#6]
## Overview

```js
while (
  !document.querySelector(
    `markdown-toolbar details-menu[src="/settings/replies?context=issue"]`
  )
) {
  await new Promise((resolve) => setTimeout(resolve, 10));
}
```

This code exists because there's a non-zero amount of time between clicking the _Saved Replies_ button and when the menu pops into existence. Asking for the menu every 10ms is a reasonable way to wait until it exists... but a more responsive, elegant way would be to use [`MutationObserver`](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) to detect the exact moment the element pops into existence.

**Comment by ad0ran** [comment]
Dibs (👉ﾟヮﾟ)👉
First time tackling an issue ԅ(¯﹃¯ԅ)

**Comment by ad0ran** [comment]
@JoshuaKGoldberg 
the dom element:
`markdown-toolbar details-menu[src="/settings/replies?context=issue"]`
seems to always exist. even inspecting the page source, that markup exists, so I'm not sure we should even be polling for its existence. I could be completely wrong here though.
Thoughts ?

**Comment by JoshuaKGoldberg** [comment]
Hmm. When I tried implementing this originally last month, that element only _seemed_ to always exist. But when I tried looking for it in code, it took a few ms after clicking to exist. Are you sure?

If it does always exist I suppose you could send a PR that removes the _"wait for the element to exist"_ code.

**Comment by ad0ran** [comment]
After inspecting the incoming document response + inspecting the page source, the element does infact exist even before javascript has had a chance to load. I even tried loading the page with javascript disabled, and the element still exists.

![image](https://user-images.githubusercontent.com/1423613/197069579-0dab3622-48f6-460b-9b12-25d62dbdd84b.png)

I'll put up a PR removing the check for it, but let me know if you're seeing different behavior
