### ISSUE TITLE
🛠 Tooling: `.nvmrc`

### ISSUE THREAD

**Issue by Pinjasaur** [JoshuaKGoldberg/refined-saved-replies#68]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/refined-saved-replies/issues?q=is%3Aissue+label%3A%22area%3A+tooling%22) and found none that matched my issue.

### Overview

Add an `.nvmrc` to enforce the correct Node version. Once added, a `nvm install` command could be ran from the repository root to use/install the correct version for the project.

**Comment by JoshuaKGoldberg** [comment]
Agreed, yes please! I also filed https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues/65 to get this into my personal standard tooling template.
